# Generated by Django 4.0.2 on 2022-02-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstRoundTime', models.DateTimeField(blank=True, null=True)),
                ('firstRoundResult', models.PositiveIntegerField(blank=True, null=True)),
                ('secondRoundTime', models.DateTimeField(blank=True, null=True)),
                ('secondRoundResult', models.PositiveIntegerField(blank=True, null=True)),
                ('pusblished', models.CharField(blank=True, choices=[('draft', 'draft'), ('published', 'published')], max_length=10, null=True)),
            ],
        ),
    ]
