# Generated by Django 4.0.2 on 2022-02-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstRounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_time', models.DateTimeField(blank=True, null=True)),
                ('winning_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_time', models.DateTimeField(blank=True, null=True)),
                ('winning_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
