# Generated by Django 4.0.2 on 2022-02-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_firstrounds_secondround'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirstRounds',
            new_name='FirstRound',
        ),
    ]
