# Generated by Django 4.0.2 on 2022-02-22 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_rename_firstrounds_firstround'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyresult',
            name='firstRoundResult',
        ),
        migrations.RemoveField(
            model_name='dailyresult',
            name='firstRoundTime',
        ),
        migrations.RemoveField(
            model_name='dailyresult',
            name='pusblished',
        ),
        migrations.RemoveField(
            model_name='dailyresult',
            name='secondRoundResult',
        ),
        migrations.RemoveField(
            model_name='dailyresult',
            name='secondRoundTime',
        ),
        migrations.AddField(
            model_name='dailyresult',
            name='first_round',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='daily.firstround'),
        ),
        migrations.AddField(
            model_name='dailyresult',
            name='second_round',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='daily.secondround'),
        ),
    ]
