# Generated by Django 4.0.2 on 2022-02-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_remove_dailyresult_firstroundresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyresult',
            name='published',
            field=models.CharField(blank=True, choices=[('draft', 'draft'), ('published', 'published')], max_length=10, null=True),
        ),
    ]
