# Generated by Django 4.0.2 on 2022-03-05 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0007_alter_firstround_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyresult',
            old_name='published',
            new_name='status',
        ),
    ]
