# Generated by Django 4.0.2 on 2022-07-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0008_rename_published_dailyresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
