# Generated by Django 4.0.2 on 2022-07-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0010_alter_dailyresult_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(blank=True, max_length=100, null=True)),
                ('ending', models.CharField(blank=True, max_length=100, null=True)),
                ('direct', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
