# Generated by Django 4.0.2 on 2022-07-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarBallGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_number', models.BigIntegerField(blank=True, null=True)),
                ('result_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'draft'), ('published', 'published')], max_length=10, null=True)),
            ],
        ),
    ]
